// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yangnuowen1-arch/resume_back/internal/dal/model"
)

func newCandidate(db *gorm.DB, opts ...gen.DOOption) candidate {
	_candidate := candidate{}

	_candidate.candidateDo.UseDB(db, opts...)
	_candidate.candidateDo.UseModel(&model.Candidate{})

	tableName := _candidate.candidateDo.TableName()
	_candidate.ALL = field.NewAsterisk(tableName)
	_candidate.ID = field.NewInt64(tableName, "id")
	_candidate.Name = field.NewString(tableName, "name")
	_candidate.Email = field.NewString(tableName, "email")
	_candidate.Phone = field.NewString(tableName, "phone")
	_candidate.Gender = field.NewString(tableName, "gender")
	_candidate.CurrentCompany = field.NewString(tableName, "current_company")
	_candidate.CurrentPosition = field.NewString(tableName, "current_position")
	_candidate.YearsOfExperience = field.NewFloat64(tableName, "years_of_experience")
	_candidate.HighestEducation = field.NewString(tableName, "highest_education")
	_candidate.School = field.NewString(tableName, "school")
	_candidate.Major = field.NewString(tableName, "major")
	_candidate.Location = field.NewString(tableName, "location")
	_candidate.Source = field.NewString(tableName, "source")
	_candidate.CreatedAt = field.NewTime(tableName, "created_at")
	_candidate.UpdatedAt = field.NewTime(tableName, "updated_at")

	_candidate.fillFieldMap()

	return _candidate
}

type candidate struct {
	candidateDo candidateDo

	ALL               field.Asterisk
	ID                field.Int64
	Name              field.String
	Email             field.String
	Phone             field.String
	Gender            field.String
	CurrentCompany    field.String
	CurrentPosition   field.String
	YearsOfExperience field.Float64
	HighestEducation  field.String
	School            field.String
	Major             field.String
	Location          field.String
	Source            field.String
	CreatedAt         field.Time
	UpdatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (c candidate) Table(newTableName string) *candidate {
	c.candidateDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c candidate) As(alias string) *candidate {
	c.candidateDo.DO = *(c.candidateDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *candidate) updateTableName(table string) *candidate {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.Name = field.NewString(table, "name")
	c.Email = field.NewString(table, "email")
	c.Phone = field.NewString(table, "phone")
	c.Gender = field.NewString(table, "gender")
	c.CurrentCompany = field.NewString(table, "current_company")
	c.CurrentPosition = field.NewString(table, "current_position")
	c.YearsOfExperience = field.NewFloat64(table, "years_of_experience")
	c.HighestEducation = field.NewString(table, "highest_education")
	c.School = field.NewString(table, "school")
	c.Major = field.NewString(table, "major")
	c.Location = field.NewString(table, "location")
	c.Source = field.NewString(table, "source")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *candidate) WithContext(ctx context.Context) *candidateDo {
	return c.candidateDo.WithContext(ctx)
}

func (c candidate) TableName() string { return c.candidateDo.TableName() }

func (c candidate) Alias() string { return c.candidateDo.Alias() }

func (c candidate) Columns(cols ...field.Expr) gen.Columns { return c.candidateDo.Columns(cols...) }

func (c *candidate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *candidate) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 15)
	c.fieldMap["id"] = c.ID
	c.fieldMap["name"] = c.Name
	c.fieldMap["email"] = c.Email
	c.fieldMap["phone"] = c.Phone
	c.fieldMap["gender"] = c.Gender
	c.fieldMap["current_company"] = c.CurrentCompany
	c.fieldMap["current_position"] = c.CurrentPosition
	c.fieldMap["years_of_experience"] = c.YearsOfExperience
	c.fieldMap["highest_education"] = c.HighestEducation
	c.fieldMap["school"] = c.School
	c.fieldMap["major"] = c.Major
	c.fieldMap["location"] = c.Location
	c.fieldMap["source"] = c.Source
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c candidate) clone(db *gorm.DB) candidate {
	c.candidateDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c candidate) replaceDB(db *gorm.DB) candidate {
	c.candidateDo.ReplaceDB(db)
	return c
}

type candidateDo struct{ gen.DO }

func (c candidateDo) Debug() *candidateDo {
	return c.withDO(c.DO.Debug())
}

func (c candidateDo) WithContext(ctx context.Context) *candidateDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c candidateDo) ReadDB() *candidateDo {
	return c.Clauses(dbresolver.Read)
}

func (c candidateDo) WriteDB() *candidateDo {
	return c.Clauses(dbresolver.Write)
}

func (c candidateDo) Session(config *gorm.Session) *candidateDo {
	return c.withDO(c.DO.Session(config))
}

func (c candidateDo) Clauses(conds ...clause.Expression) *candidateDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c candidateDo) Returning(value interface{}, columns ...string) *candidateDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c candidateDo) Not(conds ...gen.Condition) *candidateDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c candidateDo) Or(conds ...gen.Condition) *candidateDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c candidateDo) Select(conds ...field.Expr) *candidateDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c candidateDo) Where(conds ...gen.Condition) *candidateDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c candidateDo) Order(conds ...field.Expr) *candidateDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c candidateDo) Distinct(cols ...field.Expr) *candidateDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c candidateDo) Omit(cols ...field.Expr) *candidateDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c candidateDo) Join(table schema.Tabler, on ...field.Expr) *candidateDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c candidateDo) LeftJoin(table schema.Tabler, on ...field.Expr) *candidateDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c candidateDo) RightJoin(table schema.Tabler, on ...field.Expr) *candidateDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c candidateDo) Group(cols ...field.Expr) *candidateDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c candidateDo) Having(conds ...gen.Condition) *candidateDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c candidateDo) Limit(limit int) *candidateDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c candidateDo) Offset(offset int) *candidateDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c candidateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *candidateDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c candidateDo) Unscoped() *candidateDo {
	return c.withDO(c.DO.Unscoped())
}

func (c candidateDo) Create(values ...*model.Candidate) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c candidateDo) CreateInBatches(values []*model.Candidate, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c candidateDo) Save(values ...*model.Candidate) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c candidateDo) First() (*model.Candidate, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Candidate), nil
	}
}

func (c candidateDo) Take() (*model.Candidate, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Candidate), nil
	}
}

func (c candidateDo) Last() (*model.Candidate, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Candidate), nil
	}
}

func (c candidateDo) Find() ([]*model.Candidate, error) {
	result, err := c.DO.Find()
	return result.([]*model.Candidate), err
}

func (c candidateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Candidate, err error) {
	buf := make([]*model.Candidate, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c candidateDo) FindInBatches(result *[]*model.Candidate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c candidateDo) Attrs(attrs ...field.AssignExpr) *candidateDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c candidateDo) Assign(attrs ...field.AssignExpr) *candidateDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c candidateDo) Joins(fields ...field.RelationField) *candidateDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c candidateDo) Preload(fields ...field.RelationField) *candidateDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c candidateDo) FirstOrInit() (*model.Candidate, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Candidate), nil
	}
}

func (c candidateDo) FirstOrCreate() (*model.Candidate, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Candidate), nil
	}
}

func (c candidateDo) FindByPage(offset int, limit int) (result []*model.Candidate, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c candidateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c candidateDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c candidateDo) Delete(models ...*model.Candidate) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *candidateDo) withDO(do gen.Dao) *candidateDo {
	c.DO = *do.(*gen.DO)
	return c
}
