// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		Application:     newApplication(db, opts...),
		Candidate:       newCandidate(db, opts...),
		Job:             newJob(db, opts...),
		JobCategory:     newJobCategory(db, opts...),
		JobMember:       newJobMember(db, opts...),
		JobTag:          newJobTag(db, opts...),
		OperationLog:    newOperationLog(db, opts...),
		Resume:          newResume(db, opts...),
		Role:            newRole(db, opts...),
		ScreeningResult: newScreeningResult(db, opts...),
		Tag:             newTag(db, opts...),
		TagGroup:        newTagGroup(db, opts...),
		User:            newUser(db, opts...),
		UserRole:        newUserRole(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Application     application
	Candidate       candidate
	Job             job
	JobCategory     jobCategory
	JobMember       jobMember
	JobTag          jobTag
	OperationLog    operationLog
	Resume          resume
	Role            role
	ScreeningResult screeningResult
	Tag             tag
	TagGroup        tagGroup
	User            user
	UserRole        userRole
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Application:     q.Application.clone(db),
		Candidate:       q.Candidate.clone(db),
		Job:             q.Job.clone(db),
		JobCategory:     q.JobCategory.clone(db),
		JobMember:       q.JobMember.clone(db),
		JobTag:          q.JobTag.clone(db),
		OperationLog:    q.OperationLog.clone(db),
		Resume:          q.Resume.clone(db),
		Role:            q.Role.clone(db),
		ScreeningResult: q.ScreeningResult.clone(db),
		Tag:             q.Tag.clone(db),
		TagGroup:        q.TagGroup.clone(db),
		User:            q.User.clone(db),
		UserRole:        q.UserRole.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Application:     q.Application.replaceDB(db),
		Candidate:       q.Candidate.replaceDB(db),
		Job:             q.Job.replaceDB(db),
		JobCategory:     q.JobCategory.replaceDB(db),
		JobMember:       q.JobMember.replaceDB(db),
		JobTag:          q.JobTag.replaceDB(db),
		OperationLog:    q.OperationLog.replaceDB(db),
		Resume:          q.Resume.replaceDB(db),
		Role:            q.Role.replaceDB(db),
		ScreeningResult: q.ScreeningResult.replaceDB(db),
		Tag:             q.Tag.replaceDB(db),
		TagGroup:        q.TagGroup.replaceDB(db),
		User:            q.User.replaceDB(db),
		UserRole:        q.UserRole.replaceDB(db),
	}
}

type queryCtx struct {
	Application     *applicationDo
	Candidate       *candidateDo
	Job             *jobDo
	JobCategory     *jobCategoryDo
	JobMember       *jobMemberDo
	JobTag          *jobTagDo
	OperationLog    *operationLogDo
	Resume          *resumeDo
	Role            *roleDo
	ScreeningResult *screeningResultDo
	Tag             *tagDo
	TagGroup        *tagGroupDo
	User            *userDo
	UserRole        *userRoleDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Application:     q.Application.WithContext(ctx),
		Candidate:       q.Candidate.WithContext(ctx),
		Job:             q.Job.WithContext(ctx),
		JobCategory:     q.JobCategory.WithContext(ctx),
		JobMember:       q.JobMember.WithContext(ctx),
		JobTag:          q.JobTag.WithContext(ctx),
		OperationLog:    q.OperationLog.WithContext(ctx),
		Resume:          q.Resume.WithContext(ctx),
		Role:            q.Role.WithContext(ctx),
		ScreeningResult: q.ScreeningResult.WithContext(ctx),
		Tag:             q.Tag.WithContext(ctx),
		TagGroup:        q.TagGroup.WithContext(ctx),
		User:            q.User.WithContext(ctx),
		UserRole:        q.UserRole.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
