// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yangnuowen1-arch/resume_back/internal/dal/model"
)

func newJobMember(db *gorm.DB, opts ...gen.DOOption) jobMember {
	_jobMember := jobMember{}

	_jobMember.jobMemberDo.UseDB(db, opts...)
	_jobMember.jobMemberDo.UseModel(&model.JobMember{})

	tableName := _jobMember.jobMemberDo.TableName()
	_jobMember.ALL = field.NewAsterisk(tableName)
	_jobMember.ID = field.NewInt64(tableName, "id")
	_jobMember.JobID = field.NewInt64(tableName, "job_id")
	_jobMember.UserID = field.NewInt64(tableName, "user_id")
	_jobMember.MemberRole = field.NewString(tableName, "member_role")
	_jobMember.CreatedBy = field.NewInt64(tableName, "created_by")
	_jobMember.CreatedAt = field.NewTime(tableName, "created_at")

	_jobMember.fillFieldMap()

	return _jobMember
}

type jobMember struct {
	jobMemberDo jobMemberDo

	ALL        field.Asterisk
	ID         field.Int64
	JobID      field.Int64
	UserID     field.Int64
	MemberRole field.String
	CreatedBy  field.Int64
	CreatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (j jobMember) Table(newTableName string) *jobMember {
	j.jobMemberDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j jobMember) As(alias string) *jobMember {
	j.jobMemberDo.DO = *(j.jobMemberDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *jobMember) updateTableName(table string) *jobMember {
	j.ALL = field.NewAsterisk(table)
	j.ID = field.NewInt64(table, "id")
	j.JobID = field.NewInt64(table, "job_id")
	j.UserID = field.NewInt64(table, "user_id")
	j.MemberRole = field.NewString(table, "member_role")
	j.CreatedBy = field.NewInt64(table, "created_by")
	j.CreatedAt = field.NewTime(table, "created_at")

	j.fillFieldMap()

	return j
}

func (j *jobMember) WithContext(ctx context.Context) *jobMemberDo {
	return j.jobMemberDo.WithContext(ctx)
}

func (j jobMember) TableName() string { return j.jobMemberDo.TableName() }

func (j jobMember) Alias() string { return j.jobMemberDo.Alias() }

func (j jobMember) Columns(cols ...field.Expr) gen.Columns { return j.jobMemberDo.Columns(cols...) }

func (j *jobMember) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *jobMember) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 6)
	j.fieldMap["id"] = j.ID
	j.fieldMap["job_id"] = j.JobID
	j.fieldMap["user_id"] = j.UserID
	j.fieldMap["member_role"] = j.MemberRole
	j.fieldMap["created_by"] = j.CreatedBy
	j.fieldMap["created_at"] = j.CreatedAt
}

func (j jobMember) clone(db *gorm.DB) jobMember {
	j.jobMemberDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j jobMember) replaceDB(db *gorm.DB) jobMember {
	j.jobMemberDo.ReplaceDB(db)
	return j
}

type jobMemberDo struct{ gen.DO }

func (j jobMemberDo) Debug() *jobMemberDo {
	return j.withDO(j.DO.Debug())
}

func (j jobMemberDo) WithContext(ctx context.Context) *jobMemberDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j jobMemberDo) ReadDB() *jobMemberDo {
	return j.Clauses(dbresolver.Read)
}

func (j jobMemberDo) WriteDB() *jobMemberDo {
	return j.Clauses(dbresolver.Write)
}

func (j jobMemberDo) Session(config *gorm.Session) *jobMemberDo {
	return j.withDO(j.DO.Session(config))
}

func (j jobMemberDo) Clauses(conds ...clause.Expression) *jobMemberDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j jobMemberDo) Returning(value interface{}, columns ...string) *jobMemberDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j jobMemberDo) Not(conds ...gen.Condition) *jobMemberDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j jobMemberDo) Or(conds ...gen.Condition) *jobMemberDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j jobMemberDo) Select(conds ...field.Expr) *jobMemberDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j jobMemberDo) Where(conds ...gen.Condition) *jobMemberDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j jobMemberDo) Order(conds ...field.Expr) *jobMemberDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j jobMemberDo) Distinct(cols ...field.Expr) *jobMemberDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j jobMemberDo) Omit(cols ...field.Expr) *jobMemberDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j jobMemberDo) Join(table schema.Tabler, on ...field.Expr) *jobMemberDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j jobMemberDo) LeftJoin(table schema.Tabler, on ...field.Expr) *jobMemberDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j jobMemberDo) RightJoin(table schema.Tabler, on ...field.Expr) *jobMemberDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j jobMemberDo) Group(cols ...field.Expr) *jobMemberDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j jobMemberDo) Having(conds ...gen.Condition) *jobMemberDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j jobMemberDo) Limit(limit int) *jobMemberDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j jobMemberDo) Offset(offset int) *jobMemberDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j jobMemberDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *jobMemberDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j jobMemberDo) Unscoped() *jobMemberDo {
	return j.withDO(j.DO.Unscoped())
}

func (j jobMemberDo) Create(values ...*model.JobMember) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j jobMemberDo) CreateInBatches(values []*model.JobMember, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j jobMemberDo) Save(values ...*model.JobMember) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j jobMemberDo) First() (*model.JobMember, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobMember), nil
	}
}

func (j jobMemberDo) Take() (*model.JobMember, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobMember), nil
	}
}

func (j jobMemberDo) Last() (*model.JobMember, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobMember), nil
	}
}

func (j jobMemberDo) Find() ([]*model.JobMember, error) {
	result, err := j.DO.Find()
	return result.([]*model.JobMember), err
}

func (j jobMemberDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.JobMember, err error) {
	buf := make([]*model.JobMember, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j jobMemberDo) FindInBatches(result *[]*model.JobMember, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j jobMemberDo) Attrs(attrs ...field.AssignExpr) *jobMemberDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j jobMemberDo) Assign(attrs ...field.AssignExpr) *jobMemberDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j jobMemberDo) Joins(fields ...field.RelationField) *jobMemberDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j jobMemberDo) Preload(fields ...field.RelationField) *jobMemberDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j jobMemberDo) FirstOrInit() (*model.JobMember, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobMember), nil
	}
}

func (j jobMemberDo) FirstOrCreate() (*model.JobMember, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobMember), nil
	}
}

func (j jobMemberDo) FindByPage(offset int, limit int) (result []*model.JobMember, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j jobMemberDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j jobMemberDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j jobMemberDo) Delete(models ...*model.JobMember) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *jobMemberDo) withDO(do gen.Dao) *jobMemberDo {
	j.DO = *do.(*gen.DO)
	return j
}
