// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yangnuowen1-arch/resume_back/internal/dal/model"
)

func newJobCategory(db *gorm.DB, opts ...gen.DOOption) jobCategory {
	_jobCategory := jobCategory{}

	_jobCategory.jobCategoryDo.UseDB(db, opts...)
	_jobCategory.jobCategoryDo.UseModel(&model.JobCategory{})

	tableName := _jobCategory.jobCategoryDo.TableName()
	_jobCategory.ALL = field.NewAsterisk(tableName)
	_jobCategory.ID = field.NewInt64(tableName, "id")
	_jobCategory.Name = field.NewString(tableName, "name")
	_jobCategory.Description = field.NewString(tableName, "description")
	_jobCategory.ParentID = field.NewInt64(tableName, "parent_id")
	_jobCategory.SortOrder = field.NewInt32(tableName, "sort_order")
	_jobCategory.Status = field.NewString(tableName, "status")
	_jobCategory.CreatedBy = field.NewInt64(tableName, "created_by")
	_jobCategory.CreatedAt = field.NewTime(tableName, "created_at")
	_jobCategory.UpdatedAt = field.NewTime(tableName, "updated_at")

	_jobCategory.fillFieldMap()

	return _jobCategory
}

type jobCategory struct {
	jobCategoryDo jobCategoryDo

	ALL         field.Asterisk
	ID          field.Int64
	Name        field.String
	Description field.String
	ParentID    field.Int64
	SortOrder   field.Int32
	Status      field.String
	CreatedBy   field.Int64
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (j jobCategory) Table(newTableName string) *jobCategory {
	j.jobCategoryDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j jobCategory) As(alias string) *jobCategory {
	j.jobCategoryDo.DO = *(j.jobCategoryDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *jobCategory) updateTableName(table string) *jobCategory {
	j.ALL = field.NewAsterisk(table)
	j.ID = field.NewInt64(table, "id")
	j.Name = field.NewString(table, "name")
	j.Description = field.NewString(table, "description")
	j.ParentID = field.NewInt64(table, "parent_id")
	j.SortOrder = field.NewInt32(table, "sort_order")
	j.Status = field.NewString(table, "status")
	j.CreatedBy = field.NewInt64(table, "created_by")
	j.CreatedAt = field.NewTime(table, "created_at")
	j.UpdatedAt = field.NewTime(table, "updated_at")

	j.fillFieldMap()

	return j
}

func (j *jobCategory) WithContext(ctx context.Context) *jobCategoryDo {
	return j.jobCategoryDo.WithContext(ctx)
}

func (j jobCategory) TableName() string { return j.jobCategoryDo.TableName() }

func (j jobCategory) Alias() string { return j.jobCategoryDo.Alias() }

func (j jobCategory) Columns(cols ...field.Expr) gen.Columns { return j.jobCategoryDo.Columns(cols...) }

func (j *jobCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *jobCategory) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 9)
	j.fieldMap["id"] = j.ID
	j.fieldMap["name"] = j.Name
	j.fieldMap["description"] = j.Description
	j.fieldMap["parent_id"] = j.ParentID
	j.fieldMap["sort_order"] = j.SortOrder
	j.fieldMap["status"] = j.Status
	j.fieldMap["created_by"] = j.CreatedBy
	j.fieldMap["created_at"] = j.CreatedAt
	j.fieldMap["updated_at"] = j.UpdatedAt
}

func (j jobCategory) clone(db *gorm.DB) jobCategory {
	j.jobCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j jobCategory) replaceDB(db *gorm.DB) jobCategory {
	j.jobCategoryDo.ReplaceDB(db)
	return j
}

type jobCategoryDo struct{ gen.DO }

func (j jobCategoryDo) Debug() *jobCategoryDo {
	return j.withDO(j.DO.Debug())
}

func (j jobCategoryDo) WithContext(ctx context.Context) *jobCategoryDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j jobCategoryDo) ReadDB() *jobCategoryDo {
	return j.Clauses(dbresolver.Read)
}

func (j jobCategoryDo) WriteDB() *jobCategoryDo {
	return j.Clauses(dbresolver.Write)
}

func (j jobCategoryDo) Session(config *gorm.Session) *jobCategoryDo {
	return j.withDO(j.DO.Session(config))
}

func (j jobCategoryDo) Clauses(conds ...clause.Expression) *jobCategoryDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j jobCategoryDo) Returning(value interface{}, columns ...string) *jobCategoryDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j jobCategoryDo) Not(conds ...gen.Condition) *jobCategoryDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j jobCategoryDo) Or(conds ...gen.Condition) *jobCategoryDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j jobCategoryDo) Select(conds ...field.Expr) *jobCategoryDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j jobCategoryDo) Where(conds ...gen.Condition) *jobCategoryDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j jobCategoryDo) Order(conds ...field.Expr) *jobCategoryDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j jobCategoryDo) Distinct(cols ...field.Expr) *jobCategoryDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j jobCategoryDo) Omit(cols ...field.Expr) *jobCategoryDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j jobCategoryDo) Join(table schema.Tabler, on ...field.Expr) *jobCategoryDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j jobCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *jobCategoryDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j jobCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) *jobCategoryDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j jobCategoryDo) Group(cols ...field.Expr) *jobCategoryDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j jobCategoryDo) Having(conds ...gen.Condition) *jobCategoryDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j jobCategoryDo) Limit(limit int) *jobCategoryDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j jobCategoryDo) Offset(offset int) *jobCategoryDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j jobCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *jobCategoryDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j jobCategoryDo) Unscoped() *jobCategoryDo {
	return j.withDO(j.DO.Unscoped())
}

func (j jobCategoryDo) Create(values ...*model.JobCategory) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j jobCategoryDo) CreateInBatches(values []*model.JobCategory, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j jobCategoryDo) Save(values ...*model.JobCategory) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j jobCategoryDo) First() (*model.JobCategory, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobCategory), nil
	}
}

func (j jobCategoryDo) Take() (*model.JobCategory, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobCategory), nil
	}
}

func (j jobCategoryDo) Last() (*model.JobCategory, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobCategory), nil
	}
}

func (j jobCategoryDo) Find() ([]*model.JobCategory, error) {
	result, err := j.DO.Find()
	return result.([]*model.JobCategory), err
}

func (j jobCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.JobCategory, err error) {
	buf := make([]*model.JobCategory, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j jobCategoryDo) FindInBatches(result *[]*model.JobCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j jobCategoryDo) Attrs(attrs ...field.AssignExpr) *jobCategoryDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j jobCategoryDo) Assign(attrs ...field.AssignExpr) *jobCategoryDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j jobCategoryDo) Joins(fields ...field.RelationField) *jobCategoryDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j jobCategoryDo) Preload(fields ...field.RelationField) *jobCategoryDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j jobCategoryDo) FirstOrInit() (*model.JobCategory, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobCategory), nil
	}
}

func (j jobCategoryDo) FirstOrCreate() (*model.JobCategory, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobCategory), nil
	}
}

func (j jobCategoryDo) FindByPage(offset int, limit int) (result []*model.JobCategory, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j jobCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j jobCategoryDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j jobCategoryDo) Delete(models ...*model.JobCategory) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *jobCategoryDo) withDO(do gen.Dao) *jobCategoryDo {
	j.DO = *do.(*gen.DO)
	return j
}
