// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yangnuowen1-arch/resume_back/internal/dal/model"
)

func newJobTag(db *gorm.DB, opts ...gen.DOOption) jobTag {
	_jobTag := jobTag{}

	_jobTag.jobTagDo.UseDB(db, opts...)
	_jobTag.jobTagDo.UseModel(&model.JobTag{})

	tableName := _jobTag.jobTagDo.TableName()
	_jobTag.ALL = field.NewAsterisk(tableName)
	_jobTag.JobID = field.NewInt64(tableName, "job_id")
	_jobTag.TagID = field.NewInt64(tableName, "tag_id")
	_jobTag.CreatedAt = field.NewTime(tableName, "created_at")

	_jobTag.fillFieldMap()

	return _jobTag
}

type jobTag struct {
	jobTagDo jobTagDo

	ALL       field.Asterisk
	JobID     field.Int64
	TagID     field.Int64
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (j jobTag) Table(newTableName string) *jobTag {
	j.jobTagDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j jobTag) As(alias string) *jobTag {
	j.jobTagDo.DO = *(j.jobTagDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *jobTag) updateTableName(table string) *jobTag {
	j.ALL = field.NewAsterisk(table)
	j.JobID = field.NewInt64(table, "job_id")
	j.TagID = field.NewInt64(table, "tag_id")
	j.CreatedAt = field.NewTime(table, "created_at")

	j.fillFieldMap()

	return j
}

func (j *jobTag) WithContext(ctx context.Context) *jobTagDo { return j.jobTagDo.WithContext(ctx) }

func (j jobTag) TableName() string { return j.jobTagDo.TableName() }

func (j jobTag) Alias() string { return j.jobTagDo.Alias() }

func (j jobTag) Columns(cols ...field.Expr) gen.Columns { return j.jobTagDo.Columns(cols...) }

func (j *jobTag) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *jobTag) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 3)
	j.fieldMap["job_id"] = j.JobID
	j.fieldMap["tag_id"] = j.TagID
	j.fieldMap["created_at"] = j.CreatedAt
}

func (j jobTag) clone(db *gorm.DB) jobTag {
	j.jobTagDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j jobTag) replaceDB(db *gorm.DB) jobTag {
	j.jobTagDo.ReplaceDB(db)
	return j
}

type jobTagDo struct{ gen.DO }

func (j jobTagDo) Debug() *jobTagDo {
	return j.withDO(j.DO.Debug())
}

func (j jobTagDo) WithContext(ctx context.Context) *jobTagDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j jobTagDo) ReadDB() *jobTagDo {
	return j.Clauses(dbresolver.Read)
}

func (j jobTagDo) WriteDB() *jobTagDo {
	return j.Clauses(dbresolver.Write)
}

func (j jobTagDo) Session(config *gorm.Session) *jobTagDo {
	return j.withDO(j.DO.Session(config))
}

func (j jobTagDo) Clauses(conds ...clause.Expression) *jobTagDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j jobTagDo) Returning(value interface{}, columns ...string) *jobTagDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j jobTagDo) Not(conds ...gen.Condition) *jobTagDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j jobTagDo) Or(conds ...gen.Condition) *jobTagDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j jobTagDo) Select(conds ...field.Expr) *jobTagDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j jobTagDo) Where(conds ...gen.Condition) *jobTagDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j jobTagDo) Order(conds ...field.Expr) *jobTagDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j jobTagDo) Distinct(cols ...field.Expr) *jobTagDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j jobTagDo) Omit(cols ...field.Expr) *jobTagDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j jobTagDo) Join(table schema.Tabler, on ...field.Expr) *jobTagDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j jobTagDo) LeftJoin(table schema.Tabler, on ...field.Expr) *jobTagDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j jobTagDo) RightJoin(table schema.Tabler, on ...field.Expr) *jobTagDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j jobTagDo) Group(cols ...field.Expr) *jobTagDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j jobTagDo) Having(conds ...gen.Condition) *jobTagDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j jobTagDo) Limit(limit int) *jobTagDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j jobTagDo) Offset(offset int) *jobTagDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j jobTagDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *jobTagDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j jobTagDo) Unscoped() *jobTagDo {
	return j.withDO(j.DO.Unscoped())
}

func (j jobTagDo) Create(values ...*model.JobTag) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j jobTagDo) CreateInBatches(values []*model.JobTag, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j jobTagDo) Save(values ...*model.JobTag) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j jobTagDo) First() (*model.JobTag, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobTag), nil
	}
}

func (j jobTagDo) Take() (*model.JobTag, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobTag), nil
	}
}

func (j jobTagDo) Last() (*model.JobTag, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobTag), nil
	}
}

func (j jobTagDo) Find() ([]*model.JobTag, error) {
	result, err := j.DO.Find()
	return result.([]*model.JobTag), err
}

func (j jobTagDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.JobTag, err error) {
	buf := make([]*model.JobTag, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j jobTagDo) FindInBatches(result *[]*model.JobTag, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j jobTagDo) Attrs(attrs ...field.AssignExpr) *jobTagDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j jobTagDo) Assign(attrs ...field.AssignExpr) *jobTagDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j jobTagDo) Joins(fields ...field.RelationField) *jobTagDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j jobTagDo) Preload(fields ...field.RelationField) *jobTagDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j jobTagDo) FirstOrInit() (*model.JobTag, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobTag), nil
	}
}

func (j jobTagDo) FirstOrCreate() (*model.JobTag, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobTag), nil
	}
}

func (j jobTagDo) FindByPage(offset int, limit int) (result []*model.JobTag, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j jobTagDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j jobTagDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j jobTagDo) Delete(models ...*model.JobTag) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *jobTagDo) withDO(do gen.Dao) *jobTagDo {
	j.DO = *do.(*gen.DO)
	return j
}
