// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yangnuowen1-arch/resume_back/internal/dal/model"
)

func newJob(db *gorm.DB, opts ...gen.DOOption) job {
	_job := job{}

	_job.jobDo.UseDB(db, opts...)
	_job.jobDo.UseModel(&model.Job{})

	tableName := _job.jobDo.TableName()
	_job.ALL = field.NewAsterisk(tableName)
	_job.ID = field.NewInt64(tableName, "id")
	_job.CategoryID = field.NewInt64(tableName, "category_id")
	_job.Title = field.NewString(tableName, "title")
	_job.Department = field.NewString(tableName, "department")
	_job.Headcount = field.NewInt32(tableName, "headcount")
	_job.WorkLocation = field.NewString(tableName, "work_location")
	_job.WorkType = field.NewString(tableName, "work_type")
	_job.EmploymentType = field.NewString(tableName, "employment_type")
	_job.SalaryMin = field.NewInt32(tableName, "salary_min")
	_job.SalaryMax = field.NewInt32(tableName, "salary_max")
	_job.SalaryMonths = field.NewInt32(tableName, "salary_months")
	_job.ExperienceMin = field.NewInt32(tableName, "experience_min")
	_job.ExperienceMax = field.NewInt32(tableName, "experience_max")
	_job.EducationLevel = field.NewString(tableName, "education_level")
	_job.Description = field.NewString(tableName, "description")
	_job.Responsibilities = field.NewString(tableName, "responsibilities")
	_job.Requirements = field.NewString(tableName, "requirements")
	_job.BonusPoints = field.NewString(tableName, "bonus_points")
	_job.Status = field.NewString(tableName, "status")
	_job.Priority = field.NewString(tableName, "priority")
	_job.OwnerUserID = field.NewInt64(tableName, "owner_user_id")
	_job.CreatedBy = field.NewInt64(tableName, "created_by")
	_job.PublishedAt = field.NewTime(tableName, "published_at")
	_job.ClosedAt = field.NewTime(tableName, "closed_at")
	_job.CreatedAt = field.NewTime(tableName, "created_at")
	_job.UpdatedAt = field.NewTime(tableName, "updated_at")

	_job.fillFieldMap()

	return _job
}

type job struct {
	jobDo jobDo

	ALL              field.Asterisk
	ID               field.Int64
	CategoryID       field.Int64
	Title            field.String
	Department       field.String
	Headcount        field.Int32
	WorkLocation     field.String
	WorkType         field.String
	EmploymentType   field.String
	SalaryMin        field.Int32
	SalaryMax        field.Int32
	SalaryMonths     field.Int32
	ExperienceMin    field.Int32
	ExperienceMax    field.Int32
	EducationLevel   field.String
	Description      field.String
	Responsibilities field.String
	Requirements     field.String
	BonusPoints      field.String
	Status           field.String
	Priority         field.String
	OwnerUserID      field.Int64
	CreatedBy        field.Int64
	PublishedAt      field.Time
	ClosedAt         field.Time
	CreatedAt        field.Time
	UpdatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (j job) Table(newTableName string) *job {
	j.jobDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j job) As(alias string) *job {
	j.jobDo.DO = *(j.jobDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *job) updateTableName(table string) *job {
	j.ALL = field.NewAsterisk(table)
	j.ID = field.NewInt64(table, "id")
	j.CategoryID = field.NewInt64(table, "category_id")
	j.Title = field.NewString(table, "title")
	j.Department = field.NewString(table, "department")
	j.Headcount = field.NewInt32(table, "headcount")
	j.WorkLocation = field.NewString(table, "work_location")
	j.WorkType = field.NewString(table, "work_type")
	j.EmploymentType = field.NewString(table, "employment_type")
	j.SalaryMin = field.NewInt32(table, "salary_min")
	j.SalaryMax = field.NewInt32(table, "salary_max")
	j.SalaryMonths = field.NewInt32(table, "salary_months")
	j.ExperienceMin = field.NewInt32(table, "experience_min")
	j.ExperienceMax = field.NewInt32(table, "experience_max")
	j.EducationLevel = field.NewString(table, "education_level")
	j.Description = field.NewString(table, "description")
	j.Responsibilities = field.NewString(table, "responsibilities")
	j.Requirements = field.NewString(table, "requirements")
	j.BonusPoints = field.NewString(table, "bonus_points")
	j.Status = field.NewString(table, "status")
	j.Priority = field.NewString(table, "priority")
	j.OwnerUserID = field.NewInt64(table, "owner_user_id")
	j.CreatedBy = field.NewInt64(table, "created_by")
	j.PublishedAt = field.NewTime(table, "published_at")
	j.ClosedAt = field.NewTime(table, "closed_at")
	j.CreatedAt = field.NewTime(table, "created_at")
	j.UpdatedAt = field.NewTime(table, "updated_at")

	j.fillFieldMap()

	return j
}

func (j *job) WithContext(ctx context.Context) *jobDo { return j.jobDo.WithContext(ctx) }

func (j job) TableName() string { return j.jobDo.TableName() }

func (j job) Alias() string { return j.jobDo.Alias() }

func (j job) Columns(cols ...field.Expr) gen.Columns { return j.jobDo.Columns(cols...) }

func (j *job) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *job) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 26)
	j.fieldMap["id"] = j.ID
	j.fieldMap["category_id"] = j.CategoryID
	j.fieldMap["title"] = j.Title
	j.fieldMap["department"] = j.Department
	j.fieldMap["headcount"] = j.Headcount
	j.fieldMap["work_location"] = j.WorkLocation
	j.fieldMap["work_type"] = j.WorkType
	j.fieldMap["employment_type"] = j.EmploymentType
	j.fieldMap["salary_min"] = j.SalaryMin
	j.fieldMap["salary_max"] = j.SalaryMax
	j.fieldMap["salary_months"] = j.SalaryMonths
	j.fieldMap["experience_min"] = j.ExperienceMin
	j.fieldMap["experience_max"] = j.ExperienceMax
	j.fieldMap["education_level"] = j.EducationLevel
	j.fieldMap["description"] = j.Description
	j.fieldMap["responsibilities"] = j.Responsibilities
	j.fieldMap["requirements"] = j.Requirements
	j.fieldMap["bonus_points"] = j.BonusPoints
	j.fieldMap["status"] = j.Status
	j.fieldMap["priority"] = j.Priority
	j.fieldMap["owner_user_id"] = j.OwnerUserID
	j.fieldMap["created_by"] = j.CreatedBy
	j.fieldMap["published_at"] = j.PublishedAt
	j.fieldMap["closed_at"] = j.ClosedAt
	j.fieldMap["created_at"] = j.CreatedAt
	j.fieldMap["updated_at"] = j.UpdatedAt
}

func (j job) clone(db *gorm.DB) job {
	j.jobDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j job) replaceDB(db *gorm.DB) job {
	j.jobDo.ReplaceDB(db)
	return j
}

type jobDo struct{ gen.DO }

func (j jobDo) Debug() *jobDo {
	return j.withDO(j.DO.Debug())
}

func (j jobDo) WithContext(ctx context.Context) *jobDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j jobDo) ReadDB() *jobDo {
	return j.Clauses(dbresolver.Read)
}

func (j jobDo) WriteDB() *jobDo {
	return j.Clauses(dbresolver.Write)
}

func (j jobDo) Session(config *gorm.Session) *jobDo {
	return j.withDO(j.DO.Session(config))
}

func (j jobDo) Clauses(conds ...clause.Expression) *jobDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j jobDo) Returning(value interface{}, columns ...string) *jobDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j jobDo) Not(conds ...gen.Condition) *jobDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j jobDo) Or(conds ...gen.Condition) *jobDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j jobDo) Select(conds ...field.Expr) *jobDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j jobDo) Where(conds ...gen.Condition) *jobDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j jobDo) Order(conds ...field.Expr) *jobDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j jobDo) Distinct(cols ...field.Expr) *jobDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j jobDo) Omit(cols ...field.Expr) *jobDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j jobDo) Join(table schema.Tabler, on ...field.Expr) *jobDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j jobDo) LeftJoin(table schema.Tabler, on ...field.Expr) *jobDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j jobDo) RightJoin(table schema.Tabler, on ...field.Expr) *jobDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j jobDo) Group(cols ...field.Expr) *jobDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j jobDo) Having(conds ...gen.Condition) *jobDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j jobDo) Limit(limit int) *jobDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j jobDo) Offset(offset int) *jobDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j jobDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *jobDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j jobDo) Unscoped() *jobDo {
	return j.withDO(j.DO.Unscoped())
}

func (j jobDo) Create(values ...*model.Job) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j jobDo) CreateInBatches(values []*model.Job, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j jobDo) Save(values ...*model.Job) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j jobDo) First() (*model.Job, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Job), nil
	}
}

func (j jobDo) Take() (*model.Job, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Job), nil
	}
}

func (j jobDo) Last() (*model.Job, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Job), nil
	}
}

func (j jobDo) Find() ([]*model.Job, error) {
	result, err := j.DO.Find()
	return result.([]*model.Job), err
}

func (j jobDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Job, err error) {
	buf := make([]*model.Job, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j jobDo) FindInBatches(result *[]*model.Job, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j jobDo) Attrs(attrs ...field.AssignExpr) *jobDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j jobDo) Assign(attrs ...field.AssignExpr) *jobDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j jobDo) Joins(fields ...field.RelationField) *jobDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j jobDo) Preload(fields ...field.RelationField) *jobDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j jobDo) FirstOrInit() (*model.Job, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Job), nil
	}
}

func (j jobDo) FirstOrCreate() (*model.Job, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Job), nil
	}
}

func (j jobDo) FindByPage(offset int, limit int) (result []*model.Job, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j jobDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j jobDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j jobDo) Delete(models ...*model.Job) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *jobDo) withDO(do gen.Dao) *jobDo {
	j.DO = *do.(*gen.DO)
	return j
}
