// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yangnuowen1-arch/resume_back/internal/dal/model"
)

func newMailboxScanTask(db *gorm.DB, opts ...gen.DOOption) mailboxScanTask {
	_mailboxScanTask := mailboxScanTask{}

	_mailboxScanTask.mailboxScanTaskDo.UseDB(db, opts...)
	_mailboxScanTask.mailboxScanTaskDo.UseModel(&model.MailboxScanTask{})

	tableName := _mailboxScanTask.mailboxScanTaskDo.TableName()
	_mailboxScanTask.ALL = field.NewAsterisk(tableName)
	_mailboxScanTask.ID = field.NewInt64(tableName, "id")
	_mailboxScanTask.AccountID = field.NewInt64(tableName, "account_id")
	_mailboxScanTask.TriggerSource = field.NewString(tableName, "trigger_source")
	_mailboxScanTask.Status = field.NewString(tableName, "status")
	_mailboxScanTask.Scanned = field.NewInt32(tableName, "scanned")
	_mailboxScanTask.Imported = field.NewInt32(tableName, "imported")
	_mailboxScanTask.Skipped = field.NewInt32(tableName, "skipped")
	_mailboxScanTask.Error = field.NewString(tableName, "error")
	_mailboxScanTask.StartedAt = field.NewTime(tableName, "started_at")
	_mailboxScanTask.FinishedAt = field.NewTime(tableName, "finished_at")
	_mailboxScanTask.CreatedAt = field.NewTime(tableName, "created_at")
	_mailboxScanTask.UpdatedAt = field.NewTime(tableName, "updated_at")

	_mailboxScanTask.fillFieldMap()

	return _mailboxScanTask
}

type mailboxScanTask struct {
	mailboxScanTaskDo mailboxScanTaskDo

	ALL           field.Asterisk
	ID            field.Int64
	AccountID     field.Int64
	TriggerSource field.String
	Status        field.String
	Scanned       field.Int32
	Imported      field.Int32
	Skipped       field.Int32
	Error         field.String
	StartedAt     field.Time
	FinishedAt    field.Time
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (m mailboxScanTask) Table(newTableName string) *mailboxScanTask {
	m.mailboxScanTaskDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mailboxScanTask) As(alias string) *mailboxScanTask {
	m.mailboxScanTaskDo.DO = *(m.mailboxScanTaskDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mailboxScanTask) updateTableName(table string) *mailboxScanTask {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.AccountID = field.NewInt64(table, "account_id")
	m.TriggerSource = field.NewString(table, "trigger_source")
	m.Status = field.NewString(table, "status")
	m.Scanned = field.NewInt32(table, "scanned")
	m.Imported = field.NewInt32(table, "imported")
	m.Skipped = field.NewInt32(table, "skipped")
	m.Error = field.NewString(table, "error")
	m.StartedAt = field.NewTime(table, "started_at")
	m.FinishedAt = field.NewTime(table, "finished_at")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *mailboxScanTask) WithContext(ctx context.Context) *mailboxScanTaskDo {
	return m.mailboxScanTaskDo.WithContext(ctx)
}

func (m mailboxScanTask) TableName() string { return m.mailboxScanTaskDo.TableName() }

func (m mailboxScanTask) Alias() string { return m.mailboxScanTaskDo.Alias() }

func (m mailboxScanTask) Columns(cols ...field.Expr) gen.Columns {
	return m.mailboxScanTaskDo.Columns(cols...)
}

func (m *mailboxScanTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mailboxScanTask) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 12)
	m.fieldMap["id"] = m.ID
	m.fieldMap["account_id"] = m.AccountID
	m.fieldMap["trigger_source"] = m.TriggerSource
	m.fieldMap["status"] = m.Status
	m.fieldMap["scanned"] = m.Scanned
	m.fieldMap["imported"] = m.Imported
	m.fieldMap["skipped"] = m.Skipped
	m.fieldMap["error"] = m.Error
	m.fieldMap["started_at"] = m.StartedAt
	m.fieldMap["finished_at"] = m.FinishedAt
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m mailboxScanTask) clone(db *gorm.DB) mailboxScanTask {
	m.mailboxScanTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mailboxScanTask) replaceDB(db *gorm.DB) mailboxScanTask {
	m.mailboxScanTaskDo.ReplaceDB(db)
	return m
}

type mailboxScanTaskDo struct{ gen.DO }

func (m mailboxScanTaskDo) Debug() *mailboxScanTaskDo {
	return m.withDO(m.DO.Debug())
}

func (m mailboxScanTaskDo) WithContext(ctx context.Context) *mailboxScanTaskDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mailboxScanTaskDo) ReadDB() *mailboxScanTaskDo {
	return m.Clauses(dbresolver.Read)
}

func (m mailboxScanTaskDo) WriteDB() *mailboxScanTaskDo {
	return m.Clauses(dbresolver.Write)
}

func (m mailboxScanTaskDo) Session(config *gorm.Session) *mailboxScanTaskDo {
	return m.withDO(m.DO.Session(config))
}

func (m mailboxScanTaskDo) Clauses(conds ...clause.Expression) *mailboxScanTaskDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mailboxScanTaskDo) Returning(value interface{}, columns ...string) *mailboxScanTaskDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mailboxScanTaskDo) Not(conds ...gen.Condition) *mailboxScanTaskDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mailboxScanTaskDo) Or(conds ...gen.Condition) *mailboxScanTaskDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mailboxScanTaskDo) Select(conds ...field.Expr) *mailboxScanTaskDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mailboxScanTaskDo) Where(conds ...gen.Condition) *mailboxScanTaskDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mailboxScanTaskDo) Order(conds ...field.Expr) *mailboxScanTaskDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mailboxScanTaskDo) Distinct(cols ...field.Expr) *mailboxScanTaskDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mailboxScanTaskDo) Omit(cols ...field.Expr) *mailboxScanTaskDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mailboxScanTaskDo) Join(table schema.Tabler, on ...field.Expr) *mailboxScanTaskDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mailboxScanTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) *mailboxScanTaskDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mailboxScanTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) *mailboxScanTaskDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mailboxScanTaskDo) Group(cols ...field.Expr) *mailboxScanTaskDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mailboxScanTaskDo) Having(conds ...gen.Condition) *mailboxScanTaskDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mailboxScanTaskDo) Limit(limit int) *mailboxScanTaskDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mailboxScanTaskDo) Offset(offset int) *mailboxScanTaskDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mailboxScanTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *mailboxScanTaskDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mailboxScanTaskDo) Unscoped() *mailboxScanTaskDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mailboxScanTaskDo) Create(values ...*model.MailboxScanTask) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mailboxScanTaskDo) CreateInBatches(values []*model.MailboxScanTask, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mailboxScanTaskDo) Save(values ...*model.MailboxScanTask) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mailboxScanTaskDo) First() (*model.MailboxScanTask, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MailboxScanTask), nil
	}
}

func (m mailboxScanTaskDo) Take() (*model.MailboxScanTask, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MailboxScanTask), nil
	}
}

func (m mailboxScanTaskDo) Last() (*model.MailboxScanTask, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MailboxScanTask), nil
	}
}

func (m mailboxScanTaskDo) Find() ([]*model.MailboxScanTask, error) {
	result, err := m.DO.Find()
	return result.([]*model.MailboxScanTask), err
}

func (m mailboxScanTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MailboxScanTask, err error) {
	buf := make([]*model.MailboxScanTask, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mailboxScanTaskDo) FindInBatches(result *[]*model.MailboxScanTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mailboxScanTaskDo) Attrs(attrs ...field.AssignExpr) *mailboxScanTaskDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mailboxScanTaskDo) Assign(attrs ...field.AssignExpr) *mailboxScanTaskDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mailboxScanTaskDo) Joins(fields ...field.RelationField) *mailboxScanTaskDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mailboxScanTaskDo) Preload(fields ...field.RelationField) *mailboxScanTaskDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mailboxScanTaskDo) FirstOrInit() (*model.MailboxScanTask, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MailboxScanTask), nil
	}
}

func (m mailboxScanTaskDo) FirstOrCreate() (*model.MailboxScanTask, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MailboxScanTask), nil
	}
}

func (m mailboxScanTaskDo) FindByPage(offset int, limit int) (result []*model.MailboxScanTask, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mailboxScanTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mailboxScanTaskDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mailboxScanTaskDo) Delete(models ...*model.MailboxScanTask) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mailboxScanTaskDo) withDO(do gen.Dao) *mailboxScanTaskDo {
	m.DO = *do.(*gen.DO)
	return m
}
