// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yangnuowen1-arch/resume_back/internal/dal/model"
)

func newMailboxMessage(db *gorm.DB, opts ...gen.DOOption) mailboxMessage {
	_mailboxMessage := mailboxMessage{}

	_mailboxMessage.mailboxMessageDo.UseDB(db, opts...)
	_mailboxMessage.mailboxMessageDo.UseModel(&model.MailboxMessage{})

	tableName := _mailboxMessage.mailboxMessageDo.TableName()
	_mailboxMessage.ALL = field.NewAsterisk(tableName)
	_mailboxMessage.ID = field.NewInt64(tableName, "id")
	_mailboxMessage.AccountID = field.NewInt64(tableName, "account_id")
	_mailboxMessage.MessageID = field.NewString(tableName, "message_id")
	_mailboxMessage.ProcessedAt = field.NewTime(tableName, "processed_at")

	_mailboxMessage.fillFieldMap()

	return _mailboxMessage
}

type mailboxMessage struct {
	mailboxMessageDo mailboxMessageDo

	ALL         field.Asterisk
	ID          field.Int64
	AccountID   field.Int64
	MessageID   field.String
	ProcessedAt field.Time

	fieldMap map[string]field.Expr
}

func (m mailboxMessage) Table(newTableName string) *mailboxMessage {
	m.mailboxMessageDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mailboxMessage) As(alias string) *mailboxMessage {
	m.mailboxMessageDo.DO = *(m.mailboxMessageDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mailboxMessage) updateTableName(table string) *mailboxMessage {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.AccountID = field.NewInt64(table, "account_id")
	m.MessageID = field.NewString(table, "message_id")
	m.ProcessedAt = field.NewTime(table, "processed_at")

	m.fillFieldMap()

	return m
}

func (m *mailboxMessage) WithContext(ctx context.Context) *mailboxMessageDo {
	return m.mailboxMessageDo.WithContext(ctx)
}

func (m mailboxMessage) TableName() string { return m.mailboxMessageDo.TableName() }

func (m mailboxMessage) Alias() string { return m.mailboxMessageDo.Alias() }

func (m mailboxMessage) Columns(cols ...field.Expr) gen.Columns {
	return m.mailboxMessageDo.Columns(cols...)
}

func (m *mailboxMessage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mailboxMessage) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 4)
	m.fieldMap["id"] = m.ID
	m.fieldMap["account_id"] = m.AccountID
	m.fieldMap["message_id"] = m.MessageID
	m.fieldMap["processed_at"] = m.ProcessedAt
}

func (m mailboxMessage) clone(db *gorm.DB) mailboxMessage {
	m.mailboxMessageDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mailboxMessage) replaceDB(db *gorm.DB) mailboxMessage {
	m.mailboxMessageDo.ReplaceDB(db)
	return m
}

type mailboxMessageDo struct{ gen.DO }

func (m mailboxMessageDo) Debug() *mailboxMessageDo {
	return m.withDO(m.DO.Debug())
}

func (m mailboxMessageDo) WithContext(ctx context.Context) *mailboxMessageDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mailboxMessageDo) ReadDB() *mailboxMessageDo {
	return m.Clauses(dbresolver.Read)
}

func (m mailboxMessageDo) WriteDB() *mailboxMessageDo {
	return m.Clauses(dbresolver.Write)
}

func (m mailboxMessageDo) Session(config *gorm.Session) *mailboxMessageDo {
	return m.withDO(m.DO.Session(config))
}

func (m mailboxMessageDo) Clauses(conds ...clause.Expression) *mailboxMessageDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mailboxMessageDo) Returning(value interface{}, columns ...string) *mailboxMessageDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mailboxMessageDo) Not(conds ...gen.Condition) *mailboxMessageDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mailboxMessageDo) Or(conds ...gen.Condition) *mailboxMessageDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mailboxMessageDo) Select(conds ...field.Expr) *mailboxMessageDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mailboxMessageDo) Where(conds ...gen.Condition) *mailboxMessageDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mailboxMessageDo) Order(conds ...field.Expr) *mailboxMessageDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mailboxMessageDo) Distinct(cols ...field.Expr) *mailboxMessageDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mailboxMessageDo) Omit(cols ...field.Expr) *mailboxMessageDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mailboxMessageDo) Join(table schema.Tabler, on ...field.Expr) *mailboxMessageDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mailboxMessageDo) LeftJoin(table schema.Tabler, on ...field.Expr) *mailboxMessageDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mailboxMessageDo) RightJoin(table schema.Tabler, on ...field.Expr) *mailboxMessageDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mailboxMessageDo) Group(cols ...field.Expr) *mailboxMessageDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mailboxMessageDo) Having(conds ...gen.Condition) *mailboxMessageDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mailboxMessageDo) Limit(limit int) *mailboxMessageDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mailboxMessageDo) Offset(offset int) *mailboxMessageDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mailboxMessageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *mailboxMessageDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mailboxMessageDo) Unscoped() *mailboxMessageDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mailboxMessageDo) Create(values ...*model.MailboxMessage) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mailboxMessageDo) CreateInBatches(values []*model.MailboxMessage, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mailboxMessageDo) Save(values ...*model.MailboxMessage) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mailboxMessageDo) First() (*model.MailboxMessage, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MailboxMessage), nil
	}
}

func (m mailboxMessageDo) Take() (*model.MailboxMessage, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MailboxMessage), nil
	}
}

func (m mailboxMessageDo) Last() (*model.MailboxMessage, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MailboxMessage), nil
	}
}

func (m mailboxMessageDo) Find() ([]*model.MailboxMessage, error) {
	result, err := m.DO.Find()
	return result.([]*model.MailboxMessage), err
}

func (m mailboxMessageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MailboxMessage, err error) {
	buf := make([]*model.MailboxMessage, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mailboxMessageDo) FindInBatches(result *[]*model.MailboxMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mailboxMessageDo) Attrs(attrs ...field.AssignExpr) *mailboxMessageDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mailboxMessageDo) Assign(attrs ...field.AssignExpr) *mailboxMessageDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mailboxMessageDo) Joins(fields ...field.RelationField) *mailboxMessageDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mailboxMessageDo) Preload(fields ...field.RelationField) *mailboxMessageDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mailboxMessageDo) FirstOrInit() (*model.MailboxMessage, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MailboxMessage), nil
	}
}

func (m mailboxMessageDo) FirstOrCreate() (*model.MailboxMessage, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MailboxMessage), nil
	}
}

func (m mailboxMessageDo) FindByPage(offset int, limit int) (result []*model.MailboxMessage, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mailboxMessageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mailboxMessageDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mailboxMessageDo) Delete(models ...*model.MailboxMessage) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mailboxMessageDo) withDO(do gen.Dao) *mailboxMessageDo {
	m.DO = *do.(*gen.DO)
	return m
}
