// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yangnuowen1-arch/resume_back/internal/dal/model"
)

func newMailboxAccount(db *gorm.DB, opts ...gen.DOOption) mailboxAccount {
	_mailboxAccount := mailboxAccount{}

	_mailboxAccount.mailboxAccountDo.UseDB(db, opts...)
	_mailboxAccount.mailboxAccountDo.UseModel(&model.MailboxAccount{})

	tableName := _mailboxAccount.mailboxAccountDo.TableName()
	_mailboxAccount.ALL = field.NewAsterisk(tableName)
	_mailboxAccount.ID = field.NewInt64(tableName, "id")
	_mailboxAccount.Provider = field.NewString(tableName, "provider")
	_mailboxAccount.Email = field.NewString(tableName, "email")
	_mailboxAccount.AccessToken = field.NewString(tableName, "access_token")
	_mailboxAccount.RefreshToken = field.NewString(tableName, "refresh_token")
	_mailboxAccount.TokenExpiry = field.NewTime(tableName, "token_expiry")
	_mailboxAccount.LastScanAt = field.NewTime(tableName, "last_scan_at")
	_mailboxAccount.CreatedAt = field.NewTime(tableName, "created_at")
	_mailboxAccount.UpdatedAt = field.NewTime(tableName, "updated_at")

	_mailboxAccount.fillFieldMap()

	return _mailboxAccount
}

type mailboxAccount struct {
	mailboxAccountDo mailboxAccountDo

	ALL          field.Asterisk
	ID           field.Int64
	Provider     field.String
	Email        field.String
	AccessToken  field.String
	RefreshToken field.String
	TokenExpiry  field.Time
	LastScanAt   field.Time
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (m mailboxAccount) Table(newTableName string) *mailboxAccount {
	m.mailboxAccountDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mailboxAccount) As(alias string) *mailboxAccount {
	m.mailboxAccountDo.DO = *(m.mailboxAccountDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mailboxAccount) updateTableName(table string) *mailboxAccount {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.Provider = field.NewString(table, "provider")
	m.Email = field.NewString(table, "email")
	m.AccessToken = field.NewString(table, "access_token")
	m.RefreshToken = field.NewString(table, "refresh_token")
	m.TokenExpiry = field.NewTime(table, "token_expiry")
	m.LastScanAt = field.NewTime(table, "last_scan_at")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *mailboxAccount) WithContext(ctx context.Context) *mailboxAccountDo {
	return m.mailboxAccountDo.WithContext(ctx)
}

func (m mailboxAccount) TableName() string { return m.mailboxAccountDo.TableName() }

func (m mailboxAccount) Alias() string { return m.mailboxAccountDo.Alias() }

func (m mailboxAccount) Columns(cols ...field.Expr) gen.Columns {
	return m.mailboxAccountDo.Columns(cols...)
}

func (m *mailboxAccount) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mailboxAccount) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 9)
	m.fieldMap["id"] = m.ID
	m.fieldMap["provider"] = m.Provider
	m.fieldMap["email"] = m.Email
	m.fieldMap["access_token"] = m.AccessToken
	m.fieldMap["refresh_token"] = m.RefreshToken
	m.fieldMap["token_expiry"] = m.TokenExpiry
	m.fieldMap["last_scan_at"] = m.LastScanAt
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m mailboxAccount) clone(db *gorm.DB) mailboxAccount {
	m.mailboxAccountDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mailboxAccount) replaceDB(db *gorm.DB) mailboxAccount {
	m.mailboxAccountDo.ReplaceDB(db)
	return m
}

type mailboxAccountDo struct{ gen.DO }

func (m mailboxAccountDo) Debug() *mailboxAccountDo {
	return m.withDO(m.DO.Debug())
}

func (m mailboxAccountDo) WithContext(ctx context.Context) *mailboxAccountDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mailboxAccountDo) ReadDB() *mailboxAccountDo {
	return m.Clauses(dbresolver.Read)
}

func (m mailboxAccountDo) WriteDB() *mailboxAccountDo {
	return m.Clauses(dbresolver.Write)
}

func (m mailboxAccountDo) Session(config *gorm.Session) *mailboxAccountDo {
	return m.withDO(m.DO.Session(config))
}

func (m mailboxAccountDo) Clauses(conds ...clause.Expression) *mailboxAccountDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mailboxAccountDo) Returning(value interface{}, columns ...string) *mailboxAccountDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mailboxAccountDo) Not(conds ...gen.Condition) *mailboxAccountDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mailboxAccountDo) Or(conds ...gen.Condition) *mailboxAccountDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mailboxAccountDo) Select(conds ...field.Expr) *mailboxAccountDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mailboxAccountDo) Where(conds ...gen.Condition) *mailboxAccountDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mailboxAccountDo) Order(conds ...field.Expr) *mailboxAccountDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mailboxAccountDo) Distinct(cols ...field.Expr) *mailboxAccountDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mailboxAccountDo) Omit(cols ...field.Expr) *mailboxAccountDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mailboxAccountDo) Join(table schema.Tabler, on ...field.Expr) *mailboxAccountDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mailboxAccountDo) LeftJoin(table schema.Tabler, on ...field.Expr) *mailboxAccountDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mailboxAccountDo) RightJoin(table schema.Tabler, on ...field.Expr) *mailboxAccountDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mailboxAccountDo) Group(cols ...field.Expr) *mailboxAccountDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mailboxAccountDo) Having(conds ...gen.Condition) *mailboxAccountDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mailboxAccountDo) Limit(limit int) *mailboxAccountDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mailboxAccountDo) Offset(offset int) *mailboxAccountDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mailboxAccountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *mailboxAccountDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mailboxAccountDo) Unscoped() *mailboxAccountDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mailboxAccountDo) Create(values ...*model.MailboxAccount) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mailboxAccountDo) CreateInBatches(values []*model.MailboxAccount, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mailboxAccountDo) Save(values ...*model.MailboxAccount) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mailboxAccountDo) First() (*model.MailboxAccount, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MailboxAccount), nil
	}
}

func (m mailboxAccountDo) Take() (*model.MailboxAccount, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MailboxAccount), nil
	}
}

func (m mailboxAccountDo) Last() (*model.MailboxAccount, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MailboxAccount), nil
	}
}

func (m mailboxAccountDo) Find() ([]*model.MailboxAccount, error) {
	result, err := m.DO.Find()
	return result.([]*model.MailboxAccount), err
}

func (m mailboxAccountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MailboxAccount, err error) {
	buf := make([]*model.MailboxAccount, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mailboxAccountDo) FindInBatches(result *[]*model.MailboxAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mailboxAccountDo) Attrs(attrs ...field.AssignExpr) *mailboxAccountDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mailboxAccountDo) Assign(attrs ...field.AssignExpr) *mailboxAccountDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mailboxAccountDo) Joins(fields ...field.RelationField) *mailboxAccountDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mailboxAccountDo) Preload(fields ...field.RelationField) *mailboxAccountDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mailboxAccountDo) FirstOrInit() (*model.MailboxAccount, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MailboxAccount), nil
	}
}

func (m mailboxAccountDo) FirstOrCreate() (*model.MailboxAccount, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MailboxAccount), nil
	}
}

func (m mailboxAccountDo) FindByPage(offset int, limit int) (result []*model.MailboxAccount, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mailboxAccountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mailboxAccountDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mailboxAccountDo) Delete(models ...*model.MailboxAccount) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mailboxAccountDo) withDO(do gen.Dao) *mailboxAccountDo {
	m.DO = *do.(*gen.DO)
	return m
}
