// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yangnuowen1-arch/resume_back/internal/dal/model"
)

func newMailboxMessageAttachment(db *gorm.DB, opts ...gen.DOOption) mailboxMessageAttachment {
	_mailboxMessageAttachment := mailboxMessageAttachment{}

	_mailboxMessageAttachment.mailboxMessageAttachmentDo.UseDB(db, opts...)
	_mailboxMessageAttachment.mailboxMessageAttachmentDo.UseModel(&model.MailboxMessageAttachment{})

	tableName := _mailboxMessageAttachment.mailboxMessageAttachmentDo.TableName()
	_mailboxMessageAttachment.ALL = field.NewAsterisk(tableName)
	_mailboxMessageAttachment.ID = field.NewInt64(tableName, "id")
	_mailboxMessageAttachment.MessageID = field.NewInt64(tableName, "message_id")
	_mailboxMessageAttachment.AttachmentKey = field.NewString(tableName, "attachment_key")
	_mailboxMessageAttachment.AttachmentIndex = field.NewInt32(tableName, "attachment_index")
	_mailboxMessageAttachment.Filename = field.NewString(tableName, "filename")
	_mailboxMessageAttachment.ContentType = field.NewString(tableName, "content_type")
	_mailboxMessageAttachment.FileHash = field.NewString(tableName, "file_hash")
	_mailboxMessageAttachment.ObjectKey = field.NewString(tableName, "object_key")
	_mailboxMessageAttachment.CandidateID = field.NewInt64(tableName, "candidate_id")
	_mailboxMessageAttachment.ResumeID = field.NewInt64(tableName, "resume_id")
	_mailboxMessageAttachment.CreatedAt = field.NewTime(tableName, "created_at")
	_mailboxMessageAttachment.UpdatedAt = field.NewTime(tableName, "updated_at")

	_mailboxMessageAttachment.fillFieldMap()

	return _mailboxMessageAttachment
}

type mailboxMessageAttachment struct {
	mailboxMessageAttachmentDo mailboxMessageAttachmentDo

	ALL             field.Asterisk
	ID              field.Int64
	MessageID       field.Int64
	AttachmentKey   field.String
	AttachmentIndex field.Int32
	Filename        field.String
	ContentType     field.String
	FileHash        field.String
	ObjectKey       field.String
	CandidateID     field.Int64
	ResumeID        field.Int64
	CreatedAt       field.Time
	UpdatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (m mailboxMessageAttachment) Table(newTableName string) *mailboxMessageAttachment {
	m.mailboxMessageAttachmentDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mailboxMessageAttachment) As(alias string) *mailboxMessageAttachment {
	m.mailboxMessageAttachmentDo.DO = *(m.mailboxMessageAttachmentDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mailboxMessageAttachment) updateTableName(table string) *mailboxMessageAttachment {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.MessageID = field.NewInt64(table, "message_id")
	m.AttachmentKey = field.NewString(table, "attachment_key")
	m.AttachmentIndex = field.NewInt32(table, "attachment_index")
	m.Filename = field.NewString(table, "filename")
	m.ContentType = field.NewString(table, "content_type")
	m.FileHash = field.NewString(table, "file_hash")
	m.ObjectKey = field.NewString(table, "object_key")
	m.CandidateID = field.NewInt64(table, "candidate_id")
	m.ResumeID = field.NewInt64(table, "resume_id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *mailboxMessageAttachment) WithContext(ctx context.Context) *mailboxMessageAttachmentDo {
	return m.mailboxMessageAttachmentDo.WithContext(ctx)
}

func (m mailboxMessageAttachment) TableName() string { return m.mailboxMessageAttachmentDo.TableName() }

func (m mailboxMessageAttachment) Alias() string { return m.mailboxMessageAttachmentDo.Alias() }

func (m mailboxMessageAttachment) Columns(cols ...field.Expr) gen.Columns {
	return m.mailboxMessageAttachmentDo.Columns(cols...)
}

func (m *mailboxMessageAttachment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mailboxMessageAttachment) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 12)
	m.fieldMap["id"] = m.ID
	m.fieldMap["message_id"] = m.MessageID
	m.fieldMap["attachment_key"] = m.AttachmentKey
	m.fieldMap["attachment_index"] = m.AttachmentIndex
	m.fieldMap["filename"] = m.Filename
	m.fieldMap["content_type"] = m.ContentType
	m.fieldMap["file_hash"] = m.FileHash
	m.fieldMap["object_key"] = m.ObjectKey
	m.fieldMap["candidate_id"] = m.CandidateID
	m.fieldMap["resume_id"] = m.ResumeID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m mailboxMessageAttachment) clone(db *gorm.DB) mailboxMessageAttachment {
	m.mailboxMessageAttachmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mailboxMessageAttachment) replaceDB(db *gorm.DB) mailboxMessageAttachment {
	m.mailboxMessageAttachmentDo.ReplaceDB(db)
	return m
}

type mailboxMessageAttachmentDo struct{ gen.DO }

func (m mailboxMessageAttachmentDo) Debug() *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.Debug())
}

func (m mailboxMessageAttachmentDo) WithContext(ctx context.Context) *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mailboxMessageAttachmentDo) ReadDB() *mailboxMessageAttachmentDo {
	return m.Clauses(dbresolver.Read)
}

func (m mailboxMessageAttachmentDo) WriteDB() *mailboxMessageAttachmentDo {
	return m.Clauses(dbresolver.Write)
}

func (m mailboxMessageAttachmentDo) Session(config *gorm.Session) *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.Session(config))
}

func (m mailboxMessageAttachmentDo) Clauses(conds ...clause.Expression) *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mailboxMessageAttachmentDo) Returning(value interface{}, columns ...string) *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mailboxMessageAttachmentDo) Not(conds ...gen.Condition) *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mailboxMessageAttachmentDo) Or(conds ...gen.Condition) *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mailboxMessageAttachmentDo) Select(conds ...field.Expr) *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mailboxMessageAttachmentDo) Where(conds ...gen.Condition) *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mailboxMessageAttachmentDo) Order(conds ...field.Expr) *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mailboxMessageAttachmentDo) Distinct(cols ...field.Expr) *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mailboxMessageAttachmentDo) Omit(cols ...field.Expr) *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mailboxMessageAttachmentDo) Join(table schema.Tabler, on ...field.Expr) *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mailboxMessageAttachmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mailboxMessageAttachmentDo) RightJoin(table schema.Tabler, on ...field.Expr) *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mailboxMessageAttachmentDo) Group(cols ...field.Expr) *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mailboxMessageAttachmentDo) Having(conds ...gen.Condition) *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mailboxMessageAttachmentDo) Limit(limit int) *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mailboxMessageAttachmentDo) Offset(offset int) *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mailboxMessageAttachmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mailboxMessageAttachmentDo) Unscoped() *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mailboxMessageAttachmentDo) Create(values ...*model.MailboxMessageAttachment) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mailboxMessageAttachmentDo) CreateInBatches(values []*model.MailboxMessageAttachment, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mailboxMessageAttachmentDo) Save(values ...*model.MailboxMessageAttachment) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mailboxMessageAttachmentDo) First() (*model.MailboxMessageAttachment, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MailboxMessageAttachment), nil
	}
}

func (m mailboxMessageAttachmentDo) Take() (*model.MailboxMessageAttachment, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MailboxMessageAttachment), nil
	}
}

func (m mailboxMessageAttachmentDo) Last() (*model.MailboxMessageAttachment, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MailboxMessageAttachment), nil
	}
}

func (m mailboxMessageAttachmentDo) Find() ([]*model.MailboxMessageAttachment, error) {
	result, err := m.DO.Find()
	return result.([]*model.MailboxMessageAttachment), err
}

func (m mailboxMessageAttachmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MailboxMessageAttachment, err error) {
	buf := make([]*model.MailboxMessageAttachment, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mailboxMessageAttachmentDo) FindInBatches(result *[]*model.MailboxMessageAttachment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mailboxMessageAttachmentDo) Attrs(attrs ...field.AssignExpr) *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mailboxMessageAttachmentDo) Assign(attrs ...field.AssignExpr) *mailboxMessageAttachmentDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mailboxMessageAttachmentDo) Joins(fields ...field.RelationField) *mailboxMessageAttachmentDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mailboxMessageAttachmentDo) Preload(fields ...field.RelationField) *mailboxMessageAttachmentDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mailboxMessageAttachmentDo) FirstOrInit() (*model.MailboxMessageAttachment, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MailboxMessageAttachment), nil
	}
}

func (m mailboxMessageAttachmentDo) FirstOrCreate() (*model.MailboxMessageAttachment, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MailboxMessageAttachment), nil
	}
}

func (m mailboxMessageAttachmentDo) FindByPage(offset int, limit int) (result []*model.MailboxMessageAttachment, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mailboxMessageAttachmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mailboxMessageAttachmentDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mailboxMessageAttachmentDo) Delete(models ...*model.MailboxMessageAttachment) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mailboxMessageAttachmentDo) withDO(do gen.Dao) *mailboxMessageAttachmentDo {
	m.DO = *do.(*gen.DO)
	return m
}
