// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yangnuowen1-arch/resume_back/internal/dal/model"
)

func newResume(db *gorm.DB, opts ...gen.DOOption) resume {
	_resume := resume{}

	_resume.resumeDo.UseDB(db, opts...)
	_resume.resumeDo.UseModel(&model.Resume{})

	tableName := _resume.resumeDo.TableName()
	_resume.ALL = field.NewAsterisk(tableName)
	_resume.ID = field.NewInt64(tableName, "id")
	_resume.CandidateID = field.NewInt64(tableName, "candidate_id")
	_resume.OriginalFilename = field.NewString(tableName, "original_filename")
	_resume.FileURL = field.NewString(tableName, "file_url")
	_resume.FileType = field.NewString(tableName, "file_type")
	_resume.FileSize = field.NewInt64(tableName, "file_size")
	_resume.RawText = field.NewString(tableName, "raw_text")
	_resume.ParsedData = field.NewString(tableName, "parsed_data")
	_resume.Language = field.NewString(tableName, "language")
	_resume.UploadBy = field.NewInt64(tableName, "upload_by")
	_resume.UploadedAt = field.NewTime(tableName, "uploaded_at")
	_resume.CreatedAt = field.NewTime(tableName, "created_at")
	_resume.UpdatedAt = field.NewTime(tableName, "updated_at")

	_resume.fillFieldMap()

	return _resume
}

type resume struct {
	resumeDo resumeDo

	ALL              field.Asterisk
	ID               field.Int64
	CandidateID      field.Int64
	OriginalFilename field.String
	FileURL          field.String
	FileType         field.String
	FileSize         field.Int64
	RawText          field.String
	ParsedData       field.String
	Language         field.String
	UploadBy         field.Int64
	UploadedAt       field.Time
	CreatedAt        field.Time
	UpdatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (r resume) Table(newTableName string) *resume {
	r.resumeDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resume) As(alias string) *resume {
	r.resumeDo.DO = *(r.resumeDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resume) updateTableName(table string) *resume {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.CandidateID = field.NewInt64(table, "candidate_id")
	r.OriginalFilename = field.NewString(table, "original_filename")
	r.FileURL = field.NewString(table, "file_url")
	r.FileType = field.NewString(table, "file_type")
	r.FileSize = field.NewInt64(table, "file_size")
	r.RawText = field.NewString(table, "raw_text")
	r.ParsedData = field.NewString(table, "parsed_data")
	r.Language = field.NewString(table, "language")
	r.UploadBy = field.NewInt64(table, "upload_by")
	r.UploadedAt = field.NewTime(table, "uploaded_at")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *resume) WithContext(ctx context.Context) *resumeDo { return r.resumeDo.WithContext(ctx) }

func (r resume) TableName() string { return r.resumeDo.TableName() }

func (r resume) Alias() string { return r.resumeDo.Alias() }

func (r resume) Columns(cols ...field.Expr) gen.Columns { return r.resumeDo.Columns(cols...) }

func (r *resume) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resume) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 13)
	r.fieldMap["id"] = r.ID
	r.fieldMap["candidate_id"] = r.CandidateID
	r.fieldMap["original_filename"] = r.OriginalFilename
	r.fieldMap["file_url"] = r.FileURL
	r.fieldMap["file_type"] = r.FileType
	r.fieldMap["file_size"] = r.FileSize
	r.fieldMap["raw_text"] = r.RawText
	r.fieldMap["parsed_data"] = r.ParsedData
	r.fieldMap["language"] = r.Language
	r.fieldMap["upload_by"] = r.UploadBy
	r.fieldMap["uploaded_at"] = r.UploadedAt
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r resume) clone(db *gorm.DB) resume {
	r.resumeDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r resume) replaceDB(db *gorm.DB) resume {
	r.resumeDo.ReplaceDB(db)
	return r
}

type resumeDo struct{ gen.DO }

func (r resumeDo) Debug() *resumeDo {
	return r.withDO(r.DO.Debug())
}

func (r resumeDo) WithContext(ctx context.Context) *resumeDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resumeDo) ReadDB() *resumeDo {
	return r.Clauses(dbresolver.Read)
}

func (r resumeDo) WriteDB() *resumeDo {
	return r.Clauses(dbresolver.Write)
}

func (r resumeDo) Session(config *gorm.Session) *resumeDo {
	return r.withDO(r.DO.Session(config))
}

func (r resumeDo) Clauses(conds ...clause.Expression) *resumeDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resumeDo) Returning(value interface{}, columns ...string) *resumeDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resumeDo) Not(conds ...gen.Condition) *resumeDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resumeDo) Or(conds ...gen.Condition) *resumeDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resumeDo) Select(conds ...field.Expr) *resumeDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resumeDo) Where(conds ...gen.Condition) *resumeDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resumeDo) Order(conds ...field.Expr) *resumeDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resumeDo) Distinct(cols ...field.Expr) *resumeDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resumeDo) Omit(cols ...field.Expr) *resumeDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resumeDo) Join(table schema.Tabler, on ...field.Expr) *resumeDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resumeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *resumeDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resumeDo) RightJoin(table schema.Tabler, on ...field.Expr) *resumeDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resumeDo) Group(cols ...field.Expr) *resumeDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resumeDo) Having(conds ...gen.Condition) *resumeDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resumeDo) Limit(limit int) *resumeDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resumeDo) Offset(offset int) *resumeDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resumeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *resumeDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resumeDo) Unscoped() *resumeDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resumeDo) Create(values ...*model.Resume) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resumeDo) CreateInBatches(values []*model.Resume, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resumeDo) Save(values ...*model.Resume) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resumeDo) First() (*model.Resume, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Resume), nil
	}
}

func (r resumeDo) Take() (*model.Resume, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Resume), nil
	}
}

func (r resumeDo) Last() (*model.Resume, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Resume), nil
	}
}

func (r resumeDo) Find() ([]*model.Resume, error) {
	result, err := r.DO.Find()
	return result.([]*model.Resume), err
}

func (r resumeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Resume, err error) {
	buf := make([]*model.Resume, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resumeDo) FindInBatches(result *[]*model.Resume, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resumeDo) Attrs(attrs ...field.AssignExpr) *resumeDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resumeDo) Assign(attrs ...field.AssignExpr) *resumeDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resumeDo) Joins(fields ...field.RelationField) *resumeDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resumeDo) Preload(fields ...field.RelationField) *resumeDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resumeDo) FirstOrInit() (*model.Resume, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Resume), nil
	}
}

func (r resumeDo) FirstOrCreate() (*model.Resume, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Resume), nil
	}
}

func (r resumeDo) FindByPage(offset int, limit int) (result []*model.Resume, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resumeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resumeDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resumeDo) Delete(models ...*model.Resume) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resumeDo) withDO(do gen.Dao) *resumeDo {
	r.DO = *do.(*gen.DO)
	return r
}
