// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yangnuowen1-arch/resume_back/internal/dal/model"
)

func newTagGroup(db *gorm.DB, opts ...gen.DOOption) tagGroup {
	_tagGroup := tagGroup{}

	_tagGroup.tagGroupDo.UseDB(db, opts...)
	_tagGroup.tagGroupDo.UseModel(&model.TagGroup{})

	tableName := _tagGroup.tagGroupDo.TableName()
	_tagGroup.ALL = field.NewAsterisk(tableName)
	_tagGroup.ID = field.NewInt64(tableName, "id")
	_tagGroup.Name = field.NewString(tableName, "name")
	_tagGroup.Description = field.NewString(tableName, "description")
	_tagGroup.SortOrder = field.NewInt32(tableName, "sort_order")
	_tagGroup.Status = field.NewString(tableName, "status")
	_tagGroup.CreatedBy = field.NewInt64(tableName, "created_by")
	_tagGroup.CreatedAt = field.NewTime(tableName, "created_at")
	_tagGroup.UpdatedAt = field.NewTime(tableName, "updated_at")

	_tagGroup.fillFieldMap()

	return _tagGroup
}

type tagGroup struct {
	tagGroupDo tagGroupDo

	ALL         field.Asterisk
	ID          field.Int64
	Name        field.String
	Description field.String
	SortOrder   field.Int32
	Status      field.String
	CreatedBy   field.Int64
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (t tagGroup) Table(newTableName string) *tagGroup {
	t.tagGroupDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tagGroup) As(alias string) *tagGroup {
	t.tagGroupDo.DO = *(t.tagGroupDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tagGroup) updateTableName(table string) *tagGroup {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.Name = field.NewString(table, "name")
	t.Description = field.NewString(table, "description")
	t.SortOrder = field.NewInt32(table, "sort_order")
	t.Status = field.NewString(table, "status")
	t.CreatedBy = field.NewInt64(table, "created_by")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *tagGroup) WithContext(ctx context.Context) *tagGroupDo { return t.tagGroupDo.WithContext(ctx) }

func (t tagGroup) TableName() string { return t.tagGroupDo.TableName() }

func (t tagGroup) Alias() string { return t.tagGroupDo.Alias() }

func (t tagGroup) Columns(cols ...field.Expr) gen.Columns { return t.tagGroupDo.Columns(cols...) }

func (t *tagGroup) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tagGroup) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 8)
	t.fieldMap["id"] = t.ID
	t.fieldMap["name"] = t.Name
	t.fieldMap["description"] = t.Description
	t.fieldMap["sort_order"] = t.SortOrder
	t.fieldMap["status"] = t.Status
	t.fieldMap["created_by"] = t.CreatedBy
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t tagGroup) clone(db *gorm.DB) tagGroup {
	t.tagGroupDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tagGroup) replaceDB(db *gorm.DB) tagGroup {
	t.tagGroupDo.ReplaceDB(db)
	return t
}

type tagGroupDo struct{ gen.DO }

func (t tagGroupDo) Debug() *tagGroupDo {
	return t.withDO(t.DO.Debug())
}

func (t tagGroupDo) WithContext(ctx context.Context) *tagGroupDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tagGroupDo) ReadDB() *tagGroupDo {
	return t.Clauses(dbresolver.Read)
}

func (t tagGroupDo) WriteDB() *tagGroupDo {
	return t.Clauses(dbresolver.Write)
}

func (t tagGroupDo) Session(config *gorm.Session) *tagGroupDo {
	return t.withDO(t.DO.Session(config))
}

func (t tagGroupDo) Clauses(conds ...clause.Expression) *tagGroupDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tagGroupDo) Returning(value interface{}, columns ...string) *tagGroupDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tagGroupDo) Not(conds ...gen.Condition) *tagGroupDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tagGroupDo) Or(conds ...gen.Condition) *tagGroupDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tagGroupDo) Select(conds ...field.Expr) *tagGroupDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tagGroupDo) Where(conds ...gen.Condition) *tagGroupDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tagGroupDo) Order(conds ...field.Expr) *tagGroupDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tagGroupDo) Distinct(cols ...field.Expr) *tagGroupDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tagGroupDo) Omit(cols ...field.Expr) *tagGroupDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tagGroupDo) Join(table schema.Tabler, on ...field.Expr) *tagGroupDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tagGroupDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tagGroupDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tagGroupDo) RightJoin(table schema.Tabler, on ...field.Expr) *tagGroupDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tagGroupDo) Group(cols ...field.Expr) *tagGroupDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tagGroupDo) Having(conds ...gen.Condition) *tagGroupDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tagGroupDo) Limit(limit int) *tagGroupDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tagGroupDo) Offset(offset int) *tagGroupDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tagGroupDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tagGroupDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tagGroupDo) Unscoped() *tagGroupDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tagGroupDo) Create(values ...*model.TagGroup) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tagGroupDo) CreateInBatches(values []*model.TagGroup, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tagGroupDo) Save(values ...*model.TagGroup) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tagGroupDo) First() (*model.TagGroup, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagGroup), nil
	}
}

func (t tagGroupDo) Take() (*model.TagGroup, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagGroup), nil
	}
}

func (t tagGroupDo) Last() (*model.TagGroup, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagGroup), nil
	}
}

func (t tagGroupDo) Find() ([]*model.TagGroup, error) {
	result, err := t.DO.Find()
	return result.([]*model.TagGroup), err
}

func (t tagGroupDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TagGroup, err error) {
	buf := make([]*model.TagGroup, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tagGroupDo) FindInBatches(result *[]*model.TagGroup, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tagGroupDo) Attrs(attrs ...field.AssignExpr) *tagGroupDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tagGroupDo) Assign(attrs ...field.AssignExpr) *tagGroupDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tagGroupDo) Joins(fields ...field.RelationField) *tagGroupDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tagGroupDo) Preload(fields ...field.RelationField) *tagGroupDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tagGroupDo) FirstOrInit() (*model.TagGroup, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagGroup), nil
	}
}

func (t tagGroupDo) FirstOrCreate() (*model.TagGroup, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagGroup), nil
	}
}

func (t tagGroupDo) FindByPage(offset int, limit int) (result []*model.TagGroup, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tagGroupDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tagGroupDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tagGroupDo) Delete(models ...*model.TagGroup) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tagGroupDo) withDO(do gen.Dao) *tagGroupDo {
	t.DO = *do.(*gen.DO)
	return t
}
