// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameApplication = "applications"

// Application mapped from table <applications>
type Application struct {
	ID          int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	JobID       int64     `gorm:"column:job_id;type:bigint;not null" json:"job_id"`
	CandidateID *int64    `gorm:"column:candidate_id;type:bigint" json:"candidate_id"`
	ResumeID    int64     `gorm:"column:resume_id;type:bigint;not null" json:"resume_id"`
	Source      *string   `gorm:"column:source;type:character varying(100)" json:"source"`
	Status      string    `gorm:"column:status;type:character varying(50);not null;default:received" json:"status"`
	ReceivedAt  time.Time `gorm:"column:received_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"received_at"`
	Remark      *string   `gorm:"column:remark;type:text" json:"remark"`
	CreatedBy   *int64    `gorm:"column:created_by;type:bigint" json:"created_by"`
	CreatedAt   time.Time `gorm:"column:created_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Application's table name
func (*Application) TableName() string {
	return TableNameApplication
}
