// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameJobMember = "job_members"

// JobMember mapped from table <job_members>
type JobMember struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	JobID      int64     `gorm:"column:job_id;type:bigint;not null" json:"job_id"`
	UserID     int64     `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	MemberRole string    `gorm:"column:member_role;type:character varying(50);not null" json:"member_role"`
	CreatedBy  *int64    `gorm:"column:created_by;type:bigint" json:"created_by"`
	CreatedAt  time.Time `gorm:"column:created_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName JobMember's table name
func (*JobMember) TableName() string {
	return TableNameJobMember
}
