// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameJobTag = "job_tags"

// JobTag mapped from table <job_tags>
type JobTag struct {
	JobID     int64     `gorm:"column:job_id;type:bigint;primaryKey" json:"job_id"`
	TagID     int64     `gorm:"column:tag_id;type:bigint;primaryKey" json:"tag_id"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName JobTag's table name
func (*JobTag) TableName() string {
	return TableNameJobTag
}
