// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMailboxMessageAttachment = "mailbox_message_attachments"

// MailboxMessageAttachment mapped from table <mailbox_message_attachments>
type MailboxMessageAttachment struct {
	ID              int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	MessageID       int64     `gorm:"column:message_id;type:bigint;not null" json:"message_id"`
	AttachmentKey   string    `gorm:"column:attachment_key;type:character varying(128);not null" json:"attachment_key"`
	AttachmentIndex int32     `gorm:"column:attachment_index;type:integer;not null" json:"attachment_index"`
	Filename        *string   `gorm:"column:filename;type:character varying(255)" json:"filename"`
	ContentType     *string   `gorm:"column:content_type;type:character varying(255)" json:"content_type"`
	FileHash        *string   `gorm:"column:file_hash;type:character(64)" json:"file_hash"`
	ObjectKey       *string   `gorm:"column:object_key;type:text" json:"object_key"`
	CandidateID     int64     `gorm:"column:candidate_id;type:bigint;not null" json:"candidate_id"`
	ResumeID        int64     `gorm:"column:resume_id;type:bigint;not null" json:"resume_id"`
	CreatedAt       time.Time `gorm:"column:created_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName MailboxMessageAttachment's table name
func (*MailboxMessageAttachment) TableName() string {
	return TableNameMailboxMessageAttachment
}
