// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMailboxAccount = "mailbox_accounts"

// MailboxAccount mapped from table <mailbox_accounts>
type MailboxAccount struct {
	ID           int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Provider     string     `gorm:"column:provider;type:character varying(20);not null" json:"provider"`
	Email        string     `gorm:"column:email;type:character varying(255);not null" json:"email"`
	AccessToken  string     `gorm:"column:access_token;type:text;not null" json:"access_token"`
	RefreshToken *string    `gorm:"column:refresh_token;type:text" json:"refresh_token"`
	TokenExpiry  *time.Time `gorm:"column:token_expiry;type:timestamp without time zone" json:"token_expiry"`
	LastScanAt   *time.Time `gorm:"column:last_scan_at;type:timestamp without time zone" json:"last_scan_at"`
	CreatedAt    time.Time  `gorm:"column:created_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time  `gorm:"column:updated_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName MailboxAccount's table name
func (*MailboxAccount) TableName() string {
	return TableNameMailboxAccount
}
