// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMailboxScanTask = "mailbox_scan_tasks"

// MailboxScanTask mapped from table <mailbox_scan_tasks>
type MailboxScanTask struct {
	ID            int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	AccountID     int64      `gorm:"column:account_id;type:bigint;not null" json:"account_id"`
	TriggerSource string     `gorm:"column:trigger_source;type:character varying(20);not null" json:"trigger_source"`
	Status        string     `gorm:"column:status;type:character varying(20);not null;default:pending" json:"status"`
	Scanned       int32      `gorm:"column:scanned;type:integer;not null;default:0" json:"scanned"`
	Imported      int32      `gorm:"column:imported;type:integer;not null;default:0" json:"imported"`
	Skipped       int32      `gorm:"column:skipped;type:integer;not null;default:0" json:"skipped"`
	Error         *string    `gorm:"column:error;type:text" json:"error"`
	StartedAt     *time.Time `gorm:"column:started_at;type:timestamp without time zone" json:"started_at"`
	FinishedAt    *time.Time `gorm:"column:finished_at;type:timestamp without time zone" json:"finished_at"`
	CreatedAt     time.Time  `gorm:"column:created_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time  `gorm:"column:updated_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName MailboxScanTask's table name
func (*MailboxScanTask) TableName() string {
	return TableNameMailboxScanTask
}
