// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOperationLog = "operation_logs"

// OperationLog mapped from table <operation_logs>
type OperationLog struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID     *int64    `gorm:"column:user_id;type:bigint" json:"user_id"`
	Action     string    `gorm:"column:action;type:character varying(100);not null" json:"action"`
	Module     *string   `gorm:"column:module;type:character varying(100)" json:"module"`
	TargetType *string   `gorm:"column:target_type;type:character varying(100)" json:"target_type"`
	TargetID   *int64    `gorm:"column:target_id;type:bigint" json:"target_id"`
	BeforeData *string   `gorm:"column:before_data;type:jsonb" json:"before_data"`
	AfterData  *string   `gorm:"column:after_data;type:jsonb" json:"after_data"`
	IPAddress  *string   `gorm:"column:ip_address;type:character varying(100)" json:"ip_address"`
	UserAgent  *string   `gorm:"column:user_agent;type:text" json:"user_agent"`
	CreatedAt  time.Time `gorm:"column:created_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName OperationLog's table name
func (*OperationLog) TableName() string {
	return TableNameOperationLog
}
