// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTagGroup = "tag_groups"

// TagGroup mapped from table <tag_groups>
type TagGroup struct {
	ID          int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;type:character varying(100);not null" json:"name"`
	Description *string   `gorm:"column:description;type:text" json:"description"`
	SortOrder   int32     `gorm:"column:sort_order;type:integer;not null" json:"sort_order"`
	Status      string    `gorm:"column:status;type:character varying(20);not null;default:active" json:"status"`
	CreatedBy   *int64    `gorm:"column:created_by;type:bigint" json:"created_by"`
	CreatedAt   time.Time `gorm:"column:created_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName TagGroup's table name
func (*TagGroup) TableName() string {
	return TableNameTagGroup
}
