// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTag = "tags"

// Tag mapped from table <tags>
type Tag struct {
	ID        int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	GroupID   *int64    `gorm:"column:group_id;type:bigint" json:"group_id"`
	Name      string    `gorm:"column:name;type:character varying(100);not null" json:"name"`
	Color     *string   `gorm:"column:color;type:character varying(30)" json:"color"`
	Status    string    `gorm:"column:status;type:character varying(20);not null;default:active" json:"status"`
	CreatedBy *int64    `gorm:"column:created_by;type:bigint" json:"created_by"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Tag's table name
func (*Tag) TableName() string {
	return TableNameTag
}
