// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID           int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Username     string     `gorm:"column:username;type:character varying(50);not null" json:"username"`
	Email        *string    `gorm:"column:email;type:character varying(100)" json:"email"`
	Phone        *string    `gorm:"column:phone;type:character varying(30)" json:"phone"`
	PasswordHash string     `gorm:"column:password_hash;type:text;not null" json:"password_hash"`
	RealName     *string    `gorm:"column:real_name;type:character varying(50)" json:"real_name"`
	AvatarURL    *string    `gorm:"column:avatar_url;type:text" json:"avatar_url"`
	Status       string     `gorm:"column:status;type:character varying(20);not null;default:active" json:"status"`
	LastLoginAt  *time.Time `gorm:"column:last_login_at;type:timestamp without time zone" json:"last_login_at"`
	CreatedAt    time.Time  `gorm:"column:created_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time  `gorm:"column:updated_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
